### ==================== LOCALHOST ====================

### ==================== USERS - WEEK 1 ====================

### Get all users
GET http://localhost:5000/user


### Create user
POST http://localhost:5000/user
Content-Type: application/json

{
  "email": "newuser@example.com",
  "username": "newuser",
  "name": "New User"
}


### Get user by id
GET http://localhost:5000/user/6a9c27359d997c5c40013197


### Update user
PUT http://localhost:5000/user/6a9c27359d997c5c40013197
Content-Type: application/json

{
  "email": "updated@example.com",
  "username": "updateduser",
  "name": "Updated User"
}


### Delete user
DELETE http://localhost:5000/user/6aa599f4bccb54841c94db13


### ==================== CONTACTS - WEEK 2 ====================

### Get all contacts
GET http://localhost:5000/contacts


### Create contact
POST http://localhost:5000/contacts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "favoriteColor": "Blue",
  "birthday": "1995-01-15"
}


### Get contact by id
GET http://localhost:5000/contacts/6aaa99bc7173fde307f73cb3


### Update contact
PUT http://localhost:5000/contacts/6aaa99bc7173fde307f73cb3
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Updated",
  "email": "john.updated@example.com",
  "favoriteColor": "Green",
  "birthday": "1995-01-15"
}


### Delete contact
DELETE http://localhost:5000/contacts/6aaa96584723fb4bc41106a4